repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: detect-private-key

-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.7.0
    hooks:
    -   id: setup-cfg-fmt

-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.14.0
    hooks:
    -   id: reorder-python-imports
        args: [--py39-plus, --add-import, 'from __future__ import annotations']


-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--line-length=88]
        language_version: python3.11

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        args: ["--install-types", "--non-interactive", "--ignore-missing-imports"]
